name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Release:
    runs-on: ubuntu-latest
    container: morfin/myalpine
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: |
          mv config_example.json configuration.json
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
      - name: Build
        run: |
          cd build
          cmake --build . --config Release
  Debug:
    runs-on: ubuntu-latest
    container: morfin/myalpine
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: |
          mv config_example.json configuration.json
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
      - name: Build
        run: |
          cd build
          cmake --build . --config Debug
